import QRCodeStyling from "./core/QRCodeStyling";
export * as dotTypes from "./constants/dotTypes";
export * as cornerDotTypes from "./constants/cornerDotTypes";
export * as cornerSquareTypes from "./constants/cornerSquareTypes";
export * as errorCorrectionLevels from "./constants/errorCorrectionLevels";
export * as errorCorrectionPercents from "./constants/errorCorrectionPercents";
export * as modes from "./constants/modes";
export * as qrTypes from "./constants/qrTypes";
export * as drawTypes from "./constants/drawTypes";
export * from "./types";
export default QRCodeStyling;
